# Generated by Django 4.0 on 2021-12-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticShop', '0005_alter_imagegallery_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='CosmeticShop.Product', verbose_name='Ожидаемые'),
        ),
    ]
