# Generated by Django 4.0 on 2021-12-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticShop', '0007_alter_cartproduct_cart_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosmeticShop.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CosmeticShop.cart', verbose_name='Корзина'),
        ),
    ]
